name: ✨ Feature Request
description: Suggest an idea for F-Flow Suite
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Hub (API Server)
        - Client Local (Desktop App)
        - Site (Website)
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Would significantly improve workflow)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (Few hours of work)
        - Medium (Few days of work)
        - Complex (Weeks of work)
        - Very Complex (Months of work)
        - Unknown

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups or wireframes to help explain your feature
      placeholder: Drag and drop images here...

  - type: input
    id: users
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      placeholder: e.g., Pet shop owners, Veterinarians, Administrators

  - type: textarea
    id: business_value
    attributes:
      label: Business Value
      description: What business value would this feature provide?
      placeholder: How would this feature help users or the business?

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes
      description: Any technical considerations or implementation notes
      placeholder: Technical details, API changes, database schema changes, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: I am willing to help with testing this feature
          required: false
        - label: I am willing to help with implementation (if I have the skills)
          required: false