import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

function getRootVersion() {
  const pkg = JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf8'));
  return pkg.version;
}

function upsertEnv(filePath, entries) {
  const lines = existsSync(filePath)
    ? readFileSync(filePath, 'utf8').split(/\r?\n/)
    : [];

  const map = new Map();
  for (const line of lines) {
    const m = /^([^#\s][^=]*)=(.*)$/.exec(line);
    if (m) map.set(m[1].trim(), m[2]);
  }

  for (const [key, value] of Object.entries(entries)) {
    map.set(key, String(value));
  }

  const output = [
    '# Auto-generated by scripts/sync-version.mjs',
    ...Array.from(map.entries()).map(([k, v]) => `${k}=${v}`),
    ''
  ].join('\n');

  writeFileSync(filePath, output, 'utf8');
}

function main() {
  const version = getRootVersion();
  const rootEnv = join(process.cwd(), '.env');
  const clientEnv = join(process.cwd(), 'client-local', '.env');
  const siteEnv = join(process.cwd(), 'site', '.env');

  // ERP + Site (Vite)
  upsertEnv(rootEnv, { VITE_APP_VERSION: version });
  upsertEnv(siteEnv, { VITE_APP_VERSION: version });

  // Client-Local (Nest)
  upsertEnv(clientEnv, { APP_VERSION: version, VITE_APP_VERSION: version });

  console.log(`Synced APP_VERSION/VITE_APP_VERSION to ${version}`);
}

main();

